---
apiVersion: v1
kind: Service
metadata:
  name: service-broadcast-prod
spec:
  selector:
    name: service-broadcast-prod
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      protocol: TCP