apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: channel
  namespace: staging
  labels:
    app: channel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: channel
  template:
    metadata:
      name: channel
      labels:
        name: channel
        app: channel
    spec:
      restartPolicy: Always

      containers:
        - name: channel
          image: dejankovacevic/channel-bot:latest
          imagePullPolicy: Always

          resources:
            requests:
              memory: "50Mi"
            limits:
              memory: "500Mi"

          env:
            - name: CRYPTONITE
              value: "http://10.3.246.114:80"

            - name: OFFICIAL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: official
                  key: token

          ports:
            - containerPort: 8080
              protocol: TCP

          livenessProbe:
            httpGet:
              path: /bots/status
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10

          # for L7 LB
          readinessProbe:
            httpGet:
              path: /bots/status
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10

          command:
            - "/usr/bin/java"
            - "-Ddw.channels.official.token=$(OFFICIAL_TOKEN)"
            - "-Ddw.data=$(CRYPTONITE)"
            - "-Denv=staging"
            - "-jar"
            - "channel.jar"
            - "server"
            - "/etc/channel/channel.yaml"

---
apiVersion: v1
kind: Service
metadata:
  name: channel
  namespace: staging
spec:
  selector:
    name: channel
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
