---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: channel
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: channel
    spec:
      restartPolicy: Always

      containers:
        - name: channel
          image: eu.gcr.io/wire-bot/channel:latest

          resources:
            requests:
              memory: "50Mi"
            limits:
              memory: "500Mi"

          ports:
            - name: web
              containerPort: 8080
              protocol: TCP

          ports:
            - name: admin
              containerPort: 8081
              protocol: TCP

          env:
            - name: AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: channel-knows
                  key: token

            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: channel-knows
                  key: app_secret

            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: channel-knows
                  key: keystore_password

          volumeMounts:
            - name: channel-disk
              mountPath: /var/lib/channel/crypto

            - name: channel-config
              mountPath: /etc/channel

          command:
            - "/usr/bin/java"
            - "-Ddw.server.applicationConnectors[1].keyStorePassword=$(KEYSTORE_PASSWORD)"
            - "-Ddw.auth=$(AUTH_TOKEN)"
            - "-Ddw.appSecret=$(APP_SECRET)"
            - "-Ddw.host=35.187.36.97"
            - "-jar"
            - "channel.jar"
            - "server"
            - "/etc/channel/channel.yaml"

      volumes:
        - name: channel-disk
          gcePersistentDisk:
            pdName: channel-disk
            fsType: ext4

        - name: channel-config
          configMap:
            name: channel-config

---
apiVersion: v1
kind: Service
metadata:
  name: channel
spec:
  selector:
    name: channel
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      protocol: TCP


