---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: broadcast
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: broadcast
    spec:
      restartPolicy: Always

      containers:
        - name: broadcast
          image: eu.gcr.io/wire-bot/broadcast:latest

          resources:
            requests:
              memory: "50Mi"
            limits:
              memory: "500Mi"

          env:
            - name: AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: broadcast-knows
                  key: token

            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: broadcast-knows
                  key: app_secret

            - name: KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: broadcast-knows
                  key: keystore_password

            - name: ADMIN_CONV
              valueFrom:
                configMapKeyRef:
                  name: broadcast-config
                  key: admin

          volumeMounts:
            - name: broadcast-disk
              mountPath: /var/lib/broadcast/crypto

            - name: broadcast-config
              mountPath: /etc/broadcast

          command:
            - "/usr/bin/java"
            - "-Ddw.server.applicationConnectors[1].keyStorePassword=$(KEYSTORE_PASSWORD)"
            - "-Ddw.auth=$(AUTH_TOKEN)"
            - "-Ddw.admin=$(ADMIN_CONV)"
            - "-Ddw.appSecret=$(APP_SECRET)"
            - "-jar"
            - "broadcast.jar"
            - "server"
            - "/etc/broadcast/broadcast.yaml"

      volumes:
        - name: broadcast-disk
          gcePersistentDisk:
            pdName: broadcast-disk
            fsType: ext4

        - name: broadcast-config
          configMap:
            name: broadcast-config

---
apiVersion: v1
kind: Service
metadata:
  name: broadcast
spec:
  selector:
    name: broadcast
  type: LoadBalancer
  ports:
    - name: https
      port: 443
      protocol: TCP